name: Build & Release

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build unsigned apk
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          alias: ${{ secrets.KEY_ALIAS }}
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Rename signed apk
        run: |
          cd app/build/outputs/apk/release
          mv app-release-unsigned-signed.apk vtop_ap_${{ github.ref_name }}.apk

      - name: Upload signed apk
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/vtop_ap_${{ github.ref_name }}.apk
